apiVersion: v1
kind: Service
metadata:
  name: server-svc
  labels:
    name: server-svc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: server-app
