name: Build native image
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
      - 'v*.*.*'
      - '*.*.*-*'
      - 'v*.*.*-*'
  pull_request:
    paths:
      - src/**/*
      - project.clj
      - Makefile
      - native-config
      - .github/**/*

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rinx/setup-graalvm-ce@v0.0.1
        with:
          graalvm-version: 19.3.1
          java-version: java8
      - name: Install dependencies
        run: |
          gu install native-image
          curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod a+x lein
          sudo apt-get update && sudo apt-get install -y upx
      - name: Build uberjar
        run: |
          ./lein uberjar
      - name: Build native image
        run: |
          make
          upx --lzma --best server
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: server
          path: ./server
  build-docker:
    runs-on: ubuntu-latest
    needs:
      - build-linux
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: server
          path: tmp
      - name: Build the Docker image
        run: |
          docker build -t rinx/native-substrate-server .
      - name: Login to DockerHub
        run: |
          echo ${DOCKERHUB_PASS} | docker login --username ${DOCKERHUB_USER} --password-stdin
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      - name: push to DockerHub
        if: github.ref == 'refs/heads/master'
        run: |
          docker push rinx/native-substrate-server
          docker tag rinx/native-substrate-server rinx/native-substrate-server:nightly
          docker push rinx/native-substrate-server:nightly
      - name: push to DockerHub
        if: github.event_name == 'pull_request'
        run: |
          docker push rinx/native-substrate-server
          pr_num=`cat $GITHUB_EVENT_PATH | jq -r ".number"`
          docker tag rinx/native-substrate-server rinx/native-substrate-server:pr-${pr_num}
          docker push rinx/native-substrate-server:pr-${pr_num}
