name: Build docker image
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
      - 'v*.*.*'
      - '*.*.*-*'
      - 'v*.*.*-*'
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
      - src/**
      - project.clj
      - native-config/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t rinx/native-substrate-server . --build-arg GRAALVM_VERSION=${GRAALVM_VERSION}
      env:
        GRAALVM_VERSION: '19.3.0.2-java8'
    - name: Login to DockerHub
      run: |
        echo ${DOCKERHUB_PASS} | docker login --username ${DOCKERHUB_USER} --password-stdin
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    - name: push to DockerHub
      if: github.ref == 'refs/heads/master'
      run: |
        docker push rinx/native-substrate-server
        docker tag rinx/native-substrate-server rinx/native-substrate-server:nightly
        docker push rinx/native-substrate-server:nightly
    - name: push to DockerHub
      if: github.event_name == 'pull_request'
      run: |
        docker push rinx/native-substrate-server
        pr_num=`cat $GITHUB_EVENT_PATH | jq -r ".number"`
        docker tag rinx/native-substrate-server rinx/native-substrate-server:pr-${pr_num}
        docker push rinx/native-substrate-server:pr-${pr_num}
